---
title: "Data Visualization _ MK"
author: "Mehak Khanna"
date:  "`r Sys.Date()`"
output:
  html_document:
    theme: bootstrap
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: show
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages, include=FALSE}
library(tidyverse)
library(lubridate)
library(janitor)
library(vroom)
library(skimr)
library(sf)
library(ggmap)
library(ggrepel)
library(gridExtra)
library(pander)
library(here)
library(leaflet)
library(tmap)
library(tmaptools)
library(hrbrthemes)
library(mapview)
library(viridis)
library(treemapify)
library(ggalluvial)
library(ggridges)
library(ggthemes)

library(packcircles)
library(ggplot2)
library(viridis)
library(ggiraph)
```

``` {r data_load}
#load data with information for victim and the affected age group 
victim_age_data <- read.csv("data/data_countries_age.csv")


# clean & filter the data and rename columns
victim_age_data <- victim_age_data %>%
                      janitor::clean_names() %>% 
                    # rename required columns
                      rename('above 70' = deaths_interpersonal_violence_sex_both_age_70_years_number,
                             "50 - 69" = deaths_interpersonal_violence_sex_both_age_50_69_years_number,
                             "15 - 49" = deaths_interpersonal_violence_sex_both_age_15_49_years_number,
                             "5 - 14" = deaths_interpersonal_violence_sex_both_age_5_14_years_number,
                             "under 5" = deaths_interpersonal_violence_sex_both_age_under_5_number ) %>% 
                    #filter for 2019 data
                    filter(year=="2019")



```

``` {r plot_1}
# plot to depict the cases of homicide within each age group around the world in 2019 
victim_age_data_long <- victim_age_data %>% pivot_longer(
                                cols = 4:8,
                                names_to = "age_group",
                                values_to = "count"
                              )

victim_age_data_long %>% 
  mutate(proportion = count/sum(count)) %>% 
  mutate(age_group=fct_reorder(age_group, proportion)) %>% 
  ggplot(mapping = aes(x=age_group, y=proportion, fill=age_group)) +
  geom_col()+
  theme_bw()+
  scale_fill_brewer(palette = "OrRd")

```

```{r plot_2}

# Create data
data <- victim_age_data_long %>% 
  group_by(age_group) %>% 
  summarise(count = sum(count))

# Add a column with the text you want to display for each bubble:
data$text <- paste("name: ",data$age_group, "\n", "value:", data$count, "\n", "You can add a story here!")

# Generate the layout
packing <- circleProgressiveLayout(data$count, sizetype='area')
data <- cbind(data, packing)
dat.gg <- circleLayoutVertices(packing, npoints=50)

# Make the plot with a few differences compared to the static version:
p <- ggplot() + 
  geom_polygon_interactive(data = dat.gg, aes(x,y,group = id, fill=id,tooltip = data$text[id], data_id = id),colour = "black", alpha = 0.6) +
  scale_fill_viridis() +
  geom_text(data = data, aes(x, y, label = gsub("Group_", "", age_group)), size=4, color="black") +
  theme_void() + 
  theme(legend.position="none", plot.margin=unit(c(0,0,0,0),"cm") ) + 
  coord_equal()+
  theme_bw()+
   theme(legend.position = "none") 

p

```

``` {r data_load_2}
# load data for intentional homicide
intentional_homicide_data_all <- read.csv("data/data_cts_intentional_homicide.csv")

# clean & filter the data
intentional_homicide_data <- intentional_homicide_data_all %>%
                                      janitor::clean_names() %>% 
  #keeping only count data
                                      filter(unit_of_measurement=="Counts") %>% 
  #removing unknown and combined data
                                      filter(sex == c("Female","Male")) %>% 
  #keeping only overall age data 
                                      filter(age=="Total") %>% 
  #filter for 2019 data
                                      filter(year=="2019")

```

```{r plot_3}
# plot to depict homicide share among men and women around the world in 2019
intentional_homicide_data %>% 
  mutate(proportion = value/sum(value)) %>% 
  mutate(sex=fct_reorder(sex, proportion)) %>% 
  ggplot(mapping = aes(x=sex, y=proportion, fill=sex)) +
  geom_col()+
  theme_bw()+
  scale_fill_brewer(palette = "OrRd")

```

```{r plot_4}
# plot to depict homicide share among men and women around the world in 2019 due to partner or family related homicides
intentional_homicide_data %>% 
  filter(category==c("Intimate partner or family member" ,"Intimate partner or family member: Family member" )) %>% 
  mutate(proportion = value/sum(value)) %>% 
  #mutate(sex=fct_reorder(sex, proportion)) %>% 
  ggplot(mapping = aes(x=sex, y=proportion, fill=sex)) +
  geom_col()+
  theme_bw()+
  scale_fill_brewer(palette = "OrRd")
```