---
title: "Data Visualization _ MK"
author: "Mehak Khanna"
date: "2022-11-19"
output:
  html_document:
    theme: bootstrap
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: show
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages, include=FALSE}
library(tidyverse)
library(lubridate)
library(janitor)
library(vroom)
library(skimr)
library(sf)
library(ggmap)
library(ggrepel)
library(gridExtra)
library(pander)
library(here)
library(leaflet)
library(tmap)
library(tmaptools)
library(hrbrthemes)
library(mapview)
library(viridis)
library(treemapify)
library(ggalluvial)
library(ggridges)
library(ggthemes)
```


``` {r data_load}
intentional_homicide_data_all <- read.csv("data/data_cts_intentional_homicide.csv")

intentional_homicide_data <- intentional_homicide_data %>%
                                      janitor::clean_names() %>% 
  #keeping only count data
                                      filter(unit_of_measurement=="Counts") %>% 
  #removing unknown and combined data
                                      filter(sex == c("Female","Male")) %>% 
  #keeping only overall age data 
                                      filter(age=="Total")

```


```{r plot_1}

intentional_homicide_data %>% 
  mutate(proportion = value/sum(value)) %>% 
  mutate(sex=fct_reorder(sex, proportion)) %>% 
  ggplot(mapping = aes(x=sex, y=proportion, fill=sex)) +
  geom_col()+
  theme_bw()+
  scale_fill_brewer(palette = "OrRd")

```
```{r plot_2}
intentional_homicide_data %>% 
  filter(category==c("Intimate partner or family member" ,"Intimate partner or family member: Family member" )) %>% 
  mutate(proportion = value/sum(value)) %>% 
  mutate(sex=fct_reorder(sex, proportion)) %>% 
  ggplot(mapping = aes(x=sex, y=proportion, fill=sex)) +
  geom_col()+
  theme_bw()+
  scale_fill_brewer(palette = "OrRd")
```

